# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muxterm < Formula
  desc "Web-first terminal multiplexer with MCP agent integration"
  homepage "https://github.com/kenotron-ms/muxterm"
  version "0.51.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kenotron-ms/muxterm/releases/download/v0.51.14/muxterm_darwin_amd64.tar.gz"
      sha256 "3a0e085e7dd94b8f2d28d691283b953987d93e8e3ed6de82b15d448a3ca0f20e"

      define_method(:install) do
        bin.install "muxterm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kenotron-ms/muxterm/releases/download/v0.51.14/muxterm_darwin_arm64.tar.gz"
      sha256 "b99837e857a77d547c114cbdcc5a2473daf490ad80e6cebf20e18b0d94a7ac72"

      define_method(:install) do
        bin.install "muxterm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kenotron-ms/muxterm/releases/download/v0.51.14/muxterm_linux_amd64.tar.gz"
      sha256 "3194d6fdaace08a13b0a6017980343abfda0bcfd5c84606dadf1e3bb1c08d9c3"
      define_method(:install) do
        bin.install "muxterm"
      end
    end
  end

  test do
    system "#{bin}/muxterm", "version"
  end
end
