# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muxterm < Formula
  desc "Web-first terminal multiplexer with MCP agent integration"
  homepage "https://github.com/kenotron-ms/muxterm"
  version "0.51.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kenotron-ms/muxterm/releases/download/v0.51.9/muxterm_darwin_amd64.tar.gz"
      sha256 "f0acf94c83da9984240bb9c0f7a97c6af3d1625eaeff7ebfecfab92d42dbe9b0"

      define_method(:install) do
        bin.install "muxterm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kenotron-ms/muxterm/releases/download/v0.51.9/muxterm_darwin_arm64.tar.gz"
      sha256 "8c4dcfbe454aec60b2a66b935d8c0e80841dcc3db65c5c76076c7c75945c3453"

      define_method(:install) do
        bin.install "muxterm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kenotron-ms/muxterm/releases/download/v0.51.9/muxterm_linux_amd64.tar.gz"
      sha256 "3cba52cc3f812f109f006ed3c4ab8736aecef20a949adf115ce2ec2d4f71c79b"
      define_method(:install) do
        bin.install "muxterm"
      end
    end
  end

  test do
    system "#{bin}/muxterm", "version"
  end
end
