# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Muxterm < Formula
  desc "Web-first terminal multiplexer with MCP agent integration"
  homepage "https://github.com/kenotron-ms/muxterm"
  version "0.51.55"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kenotron-ms/muxterm/releases/download/v0.51.55/muxterm_darwin_amd64.tar.gz"
      sha256 "43efe41273cb2ddd513345e06fffc9f280f47eadb93915757e9b966b85b9710b"

      define_method(:install) do
        bin.install "muxterm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kenotron-ms/muxterm/releases/download/v0.51.55/muxterm_darwin_arm64.tar.gz"
      sha256 "5a95e34a41cdede94b71eb2ea3292106980bee86aae9cf826e310f11d09ea709"

      define_method(:install) do
        bin.install "muxterm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kenotron-ms/muxterm/releases/download/v0.51.55/muxterm_linux_amd64.tar.gz"
      sha256 "cbc5f6cfaea6e927d5dd2b45b29dd0ffbca649ef76cdd14a7eab242d0f06b665"
      define_method(:install) do
        bin.install "muxterm"
      end
    end
  end

  test do
    system "#{bin}/muxterm", "version"
  end
end
